<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shyam Shankar Hemachandran Rani">
<meta name="dcterms.date" content="2023-01-17">
<meta name="description" content="Analysis and Prediction of Wage in FIFA 18-22 dataset">

<title>Quarto Demonstration</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="FifaWage_files/libs/clipboard/clipboard.min.js"></script>
<script src="FifaWage_files/libs/quarto-html/quarto.js"></script>
<script src="FifaWage_files/libs/quarto-html/popper.min.js"></script>
<script src="FifaWage_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FifaWage_files/libs/quarto-html/anchor.min.js"></script>
<link href="FifaWage_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FifaWage_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FifaWage_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FifaWage_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FifaWage_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="FifaWage_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="FifaWage_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Quarto Demonstration</h1>
                  <div>
        <div class="description">
          Analysis and Prediction of Wage in FIFA 18-22 dataset
        </div>
      </div>
                </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <a href="https://www.linkedin.com/in/shyamshankarhr/">Shyam Shankar Hemachandran Rani</a> 
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              <a href="https://www.m-datascience.mathematik-informatik-statistik.uni-muenchen.de/index.html">
              LMU Munich Data Science
              </a>
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 17, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-dataset" id="toc-the-dataset" class="nav-link active" data-scroll-target="#the-dataset"><span class="toc-section-number">1</span>  The Dataset</a>
  <ul class="collapse">
  <li><a href="#loading-packages-reading-data" id="toc-loading-packages-reading-data" class="nav-link" data-scroll-target="#loading-packages-reading-data"><span class="toc-section-number">1.1</span>  Loading Packages &amp; Reading Data</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning"><span class="toc-section-number">1.2</span>  Data Cleaning</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="toc-section-number">2</span>  Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#missing-data-analysis" id="toc-missing-data-analysis" class="nav-link" data-scroll-target="#missing-data-analysis"><span class="toc-section-number">2.1</span>  Missing Data Analysis</a></li>
  </ul></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="toc-section-number">3</span>  Feature Engineering</a>
  <ul class="collapse">
  <li><a href="#creating-new-features" id="toc-creating-new-features" class="nav-link" data-scroll-target="#creating-new-features"><span class="toc-section-number">3.1</span>  Creating New Features</a></li>
  <li><a href="#transforming-features" id="toc-transforming-features" class="nav-link" data-scroll-target="#transforming-features"><span class="toc-section-number">3.2</span>  Transforming Features</a></li>
  <li><a href="#train-test-split" id="toc-train-test-split" class="nav-link" data-scroll-target="#train-test-split"><span class="toc-section-number">3.3</span>  Train-Test Split</a></li>
  </ul></li>
  <li><a href="#fitting-regression-models" id="toc-fitting-regression-models" class="nav-link" data-scroll-target="#fitting-regression-models"><span class="toc-section-number">4</span>  Fitting Regression Models</a>
  <ul class="collapse">
  <li><a href="#linear-model" id="toc-linear-model" class="nav-link" data-scroll-target="#linear-model"><span class="toc-section-number">4.1</span>  Linear Model</a></li>
  <li><a href="#generalized-linear-models" id="toc-generalized-linear-models" class="nav-link" data-scroll-target="#generalized-linear-models"><span class="toc-section-number">4.2</span>  Generalized Linear Models</a>
  <ul class="collapse">
  <li><a href="#log-transformed-variables" id="toc-log-transformed-variables" class="nav-link" data-scroll-target="#log-transformed-variables"><span class="toc-section-number">4.2.1</span>  Log transformed variables</a></li>
  <li><a href="#gamma-distributed-response" id="toc-gamma-distributed-response" class="nav-link" data-scroll-target="#gamma-distributed-response"><span class="toc-section-number">4.2.2</span>  Gamma Distributed Response</a></li>
  <li><a href="#aic-based-step-function-for-variable-selection" id="toc-aic-based-step-function-for-variable-selection" class="nav-link" data-scroll-target="#aic-based-step-function-for-variable-selection"><span class="toc-section-number">4.2.3</span>  AIC-based step function for variable selection</a></li>
  </ul></li>
  <li><a href="#random-forest-model" id="toc-random-forest-model" class="nav-link" data-scroll-target="#random-forest-model"><span class="toc-section-number">4.3</span>  Random Forest Model</a>
  <ul class="collapse">
  <li><a href="#hyperparameter-optimization-of-random-forest-model" id="toc-hyperparameter-optimization-of-random-forest-model" class="nav-link" data-scroll-target="#hyperparameter-optimization-of-random-forest-model"><span class="toc-section-number">4.3.1</span>  Hyperparameter Optimization of Random Forest Model</a></li>
  <li><a href="#visualizing-variable-importance" id="toc-visualizing-variable-importance" class="nav-link" data-scroll-target="#visualizing-variable-importance"><span class="toc-section-number">4.3.2</span>  Visualizing variable importance</a></li>
  </ul></li>
  <li><a href="#xgboost-model" id="toc-xgboost-model" class="nav-link" data-scroll-target="#xgboost-model"><span class="toc-section-number">4.4</span>  XGBoost Model</a></li>
  </ul></li>
  <li><a href="#wage-prediction" id="toc-wage-prediction" class="nav-link" data-scroll-target="#wage-prediction"><span class="toc-section-number">5</span>  Wage Prediction</a>
  <ul class="collapse">
  <li><a href="#baseline-model-prediction" id="toc-baseline-model-prediction" class="nav-link" data-scroll-target="#baseline-model-prediction"><span class="toc-section-number">5.1</span>  Baseline Model Prediction</a></li>
  <li><a href="#linear-models-prediction" id="toc-linear-models-prediction" class="nav-link" data-scroll-target="#linear-models-prediction"><span class="toc-section-number">5.2</span>  Linear Models Prediction</a></li>
  <li><a href="#generalized-linear-models-prediction" id="toc-generalized-linear-models-prediction" class="nav-link" data-scroll-target="#generalized-linear-models-prediction"><span class="toc-section-number">5.3</span>  Generalized Linear Models Prediction</a></li>
  <li><a href="#random-forest-model-prediction" id="toc-random-forest-model-prediction" class="nav-link" data-scroll-target="#random-forest-model-prediction"><span class="toc-section-number">5.4</span>  Random Forest Model Prediction</a></li>
  <li><a href="#xgboost-model-prediction" id="toc-xgboost-model-prediction" class="nav-link" data-scroll-target="#xgboost-model-prediction"><span class="toc-section-number">5.5</span>  XGBoost Model Prediction</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="toc-section-number">5.6</span>  Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="the-dataset" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> The Dataset</h1>
<div id="fig-fifa22" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/fifa-22.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: EA SPORTS FIFA 22</figcaption><p></p>
</figure>
</div>
<p>We will be working with <a href="https://www.kaggle.com/datasets/stefanoleone992/fifa-22-complete-player-dataset">FIFA 22 complete player dataset</a> from Kaggle. Our focus will be on modelling the dependence of player’s wage on attributes like age, reputation, etc. and predict the wage of some players on out-of-sample data.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will be using the FIFA player dataset from the years 2018 till 2022.</p>
</div>
</div>
<section id="loading-packages-reading-data" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="loading-packages-reading-data"><span class="header-section-number">1.1</span> Loading Packages &amp; Reading Data</h2>
<p>As the first step, we will set a seed. This will ensure reproducibility of the stochastic processes happening in the analysis (like random sampling).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The library <a href="https://haozhu233.github.io/kableExtra/awesome_table_in_html.html">kableExtra</a> by Hao Zhu was used to format the table display in HTML.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">'rmarkdown'</span>,<span class="st">'dplyr'</span>, <span class="st">'tidyverse'</span>, <span class="st">'corrplot'</span>, <span class="st">'randomForest'</span>, <span class="st">'VIM'</span>, <span class="st">'mice'</span>, <span class="st">'kableExtra'</span>, <span class="st">'MASS'</span>, <span class="st">'MLmetrics'</span>, <span class="st">'xgboost'</span>, <span class="st">'fastDummies'</span>), <span class="at">repos =</span> <span class="st">"http://cran.us.r-project.org"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>package 'rmarkdown' successfully unpacked and MD5 sums checked
package 'dplyr' successfully unpacked and MD5 sums checked
package 'tidyverse' successfully unpacked and MD5 sums checked
package 'corrplot' successfully unpacked and MD5 sums checked
package 'randomForest' successfully unpacked and MD5 sums checked
package 'VIM' successfully unpacked and MD5 sums checked
package 'mice' successfully unpacked and MD5 sums checked
package 'kableExtra' successfully unpacked and MD5 sums checked
package 'MASS' successfully unpacked and MD5 sums checked
package 'MLmetrics' successfully unpacked and MD5 sums checked
package 'xgboost' successfully unpacked and MD5 sums checked
package 'fastDummies' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\user\AppData\Local\Temp\RtmpumR3pA\downloaded_packages</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VIM)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MLmetrics)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>get_yearfile <span class="ot">&lt;-</span> <span class="cf">function</span> (title_year) {</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  filename <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">'./data/players_'</span>,title_year,<span class="st">'.csv'</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(filename)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  df[<span class="st">"fifa_version"</span>] <span class="ot">&lt;-</span> title_year</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  df</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>df_list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>), get_yearfile)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> df_list <span class="sc">%&gt;%</span> <span class="fu">reduce</span>(bind_rows)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(df_list)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>eligible_features <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'fifa_version'</span>,  <span class="st">'value_eur'</span>,<span class="st">'wage_eur'</span> ,<span class="st">'age'</span>,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>                     <span class="st">'height_cm'</span>, <span class="st">'weight_kg'</span>, <span class="st">'league_name'</span>,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>                     <span class="st">'club_contract_valid_until'</span>, <span class="st">'club_joined'</span>, <span class="st">'preferred_foot'</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>                     <span class="st">'international_reputation'</span>,</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>                     <span class="st">'work_rate'</span>, <span class="st">'body_type'</span>, <span class="st">'release_clause_eur'</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> player_df[eligible_features]</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(player_df)  <span class="sc">%&gt;%</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_material</span>(<span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class=" lightable-material lightable-striped lightable-hover" style="font-family: &quot;Source Sans Pro&quot;, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> fifa_version </th>
   <th style="text-align:right;"> value_eur </th>
   <th style="text-align:right;"> wage_eur </th>
   <th style="text-align:right;"> age </th>
   <th style="text-align:right;"> height_cm </th>
   <th style="text-align:right;"> weight_kg </th>
   <th style="text-align:left;"> league_name </th>
   <th style="text-align:right;"> club_contract_valid_until </th>
   <th style="text-align:left;"> club_joined </th>
   <th style="text-align:left;"> preferred_foot </th>
   <th style="text-align:right;"> international_reputation </th>
   <th style="text-align:left;"> work_rate </th>
   <th style="text-align:left;"> body_type </th>
   <th style="text-align:right;"> release_clause_eur </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 9.55e+07 </td>
   <td style="text-align:right;"> 575000 </td>
   <td style="text-align:right;"> 32 </td>
   <td style="text-align:right;"> 185 </td>
   <td style="text-align:right;"> 80 </td>
   <td style="text-align:left;"> Spain Primera Division </td>
   <td style="text-align:right;"> 2021 </td>
   <td style="text-align:left;"> 2009-07-01 </td>
   <td style="text-align:left;"> Right </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:left;"> High/Low </td>
   <td style="text-align:left;"> Unique </td>
   <td style="text-align:right;"> 195800000 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 1.05e+08 </td>
   <td style="text-align:right;"> 575000 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 170 </td>
   <td style="text-align:right;"> 72 </td>
   <td style="text-align:left;"> Spain Primera Division </td>
   <td style="text-align:right;"> 2018 </td>
   <td style="text-align:left;"> 2004-07-01 </td>
   <td style="text-align:left;"> Left </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:left;"> Medium/Medium </td>
   <td style="text-align:left;"> Unique </td>
   <td style="text-align:right;"> 215300000 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 6.10e+07 </td>
   <td style="text-align:right;"> 225000 </td>
   <td style="text-align:right;"> 31 </td>
   <td style="text-align:right;"> 193 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:left;"> German 1. Bundesliga </td>
   <td style="text-align:right;"> 2021 </td>
   <td style="text-align:left;"> 2011-07-01 </td>
   <td style="text-align:left;"> Right </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:left;"> Medium/Medium </td>
   <td style="text-align:left;"> Normal (185+) </td>
   <td style="text-align:right;"> 100700000 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 9.70e+07 </td>
   <td style="text-align:right;"> 500000 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 182 </td>
   <td style="text-align:right;"> 86 </td>
   <td style="text-align:left;"> Spain Primera Division </td>
   <td style="text-align:right;"> 2021 </td>
   <td style="text-align:left;"> 2014-07-11 </td>
   <td style="text-align:left;"> Right </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:left;"> High/Medium </td>
   <td style="text-align:left;"> Normal (170-185) </td>
   <td style="text-align:right;"> 198900000 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 1.23e+08 </td>
   <td style="text-align:right;"> 275000 </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 175 </td>
   <td style="text-align:right;"> 68 </td>
   <td style="text-align:left;"> French Ligue 1 </td>
   <td style="text-align:right;"> 2022 </td>
   <td style="text-align:left;"> 2017-08-03 </td>
   <td style="text-align:left;"> Right </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:left;"> High/Medium </td>
   <td style="text-align:left;"> Unique </td>
   <td style="text-align:right;"> 236800000 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 9.20e+07 </td>
   <td style="text-align:right;"> 350000 </td>
   <td style="text-align:right;"> 28 </td>
   <td style="text-align:right;"> 185 </td>
   <td style="text-align:right;"> 79 </td>
   <td style="text-align:left;"> German 1. Bundesliga </td>
   <td style="text-align:right;"> 2021 </td>
   <td style="text-align:left;"> 2014-07-01 </td>
   <td style="text-align:left;"> Right </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:left;"> High/Medium </td>
   <td style="text-align:left;"> Normal (170-185) </td>
   <td style="text-align:right;"> 151800000 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
</section>
<section id="data-cleaning" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="data-cleaning"><span class="header-section-number">1.2</span> Data Cleaning</h2>
<p>The dataframe has 92705 rows, comprising players from 57 leagues. We will select the top 7 leagues according to <a href="https://sportzpoint.com/football/top-7-football-leagues-by-uefa-rankings/">UEFA rankings</a>. The following are the top 7 leagues:</p>
<ul>
<li>Premier League | England</li>
<li>La Liga | Spain</li>
<li>Serie A | Italy</li>
<li>Bundesliga | Germany</li>
<li>Primeira Liga | Portugal</li>
<li>Ligue 1 | France</li>
<li>Eredivisie | Netharlands</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>top_leagues <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"English Premier League"</span>, <span class="st">"Spain Primera Division"</span>, <span class="st">"Italian Serie A"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                <span class="st">"German 1. Bundesliga"</span>, <span class="st">"Portuguese Liga ZON SAGRES"</span>, <span class="st">"French Ligue 1"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Holland Eredivisie"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> player_df[player_df<span class="sc">$</span>league_name <span class="sc">%in%</span> top_leagues,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Exploratory Data Analysis</h1>
<section id="missing-data-analysis" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="missing-data-analysis"><span class="header-section-number">2.1</span> Missing Data Analysis</h2>
<p>We can find out the columns which have missing values, with the code snippet below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>miss_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(player_df)) <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>miss_cols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "value_eur"          "release_clause_eur"</code></pre>
</div>
</div>
<p>The following columns have missing values: value_eur, release_clause_eur</p>
<p>Let’s check the count of missing values compared to the total number of rows, in each version of FIFA dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>player_df <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fifa_version) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">release_clause_na =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(release_clause_eur)),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">value_na =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(value_eur)), <span class="at">row_count=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  fifa_version release_clause_na value_na row_count
         &lt;int&gt;             &lt;int&gt;    &lt;int&gt;     &lt;int&gt;
1           18               286        1      3949
2           19               220        1      3959
3           20               203        2      4018
4           21               166        2      4068
5           22               302        0      3973</code></pre>
</div>
</div>
<p>We can visualize the missing values in the following plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>aggr_plot <span class="ot">&lt;-</span> <span class="fu">aggr</span>(player_df, <span class="at">col=</span><span class="fu">c</span>(<span class="st">'#0099ff'</span>,<span class="st">'#ff6699'</span>), <span class="at">numbers=</span><span class="cn">TRUE</span>, <span class="at">sortVars=</span><span class="cn">TRUE</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels=</span><span class="fu">names</span>(player_df), <span class="at">cex.axis=</span>.<span class="dv">5</span>, <span class="at">gap=</span><span class="dv">3</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="fu">c</span>(<span class="st">"Histogram of missing data"</span>,<span class="st">"Pattern"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-missvalues" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="FifaWage_files/figure-html/fig-missvalues-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Visualzation of missing values in the dataset</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We will now impute the missing values using the <a href="https://www.rdocumentation.org/packages/mice/versions/3.15.0/topics/mice">mice package</a> in R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>imputed_data <span class="ot">&lt;-</span> <span class="fu">mice</span>(player_df,<span class="at">m=</span><span class="dv">3</span>,<span class="at">maxit=</span><span class="dv">10</span>,<span class="at">meth=</span><span class="st">'cart'</span>,<span class="at">seed=</span><span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s compare the distribution of imputed data and the original data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(imputed_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-imputeddistr" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="FifaWage_files/figure-html/fig-imputeddistr-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Distribution of the imputed data v/s original data</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-imputeddistr">Figure&nbsp;3</a> shows the distribution of imputed data (red) over the distribution of the original data (blue). We see that they follow similar distributions. So, the imputation of our missing values hasn’t adversely affected our data distribution.</p>
<p>So we replace the missing values with the imputed values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> <span class="fu">complete</span>(imputed_data, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="feature-engineering" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Feature Engineering</h1>
<section id="creating-new-features" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="creating-new-features"><span class="header-section-number">3.1</span> Creating New Features</h2>
<p>Based on the FIFA version, club_joined date and club_contract_valid_until date, we can create the following 2 features: <strong><em>contract_left_days</em></strong> and <strong><em>days_at_club</em></strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>fifa_version <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">'20'</span>, player_df<span class="sc">$</span>fifa_version, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>fifa_version <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">ISOdate</span>(player_df<span class="sc">$</span>fifa_version, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> player_df[player_df<span class="sc">$</span>club_joined<span class="sc">!=</span><span class="st">""</span>,]  <span class="co"># since some blank values were found</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>club_joined <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">ISOdate</span>(player_df<span class="sc">$</span>club_joined, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>club_contract_valid_until <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">ISOdate</span>(player_df<span class="sc">$</span>club_contract_valid_until, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>contract_left_days <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(player_df<span class="sc">$</span>club_contract_valid_until <span class="sc">-</span> player_df<span class="sc">$</span>fifa_version)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>days_at_club <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(player_df<span class="sc">$</span>fifa_version <span class="sc">-</span> player_df<span class="sc">$</span>club_joined)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(player_df[,<span class="fu">c</span>(<span class="st">"fifa_version"</span>, <span class="st">"club_joined"</span>, <span class="st">"club_contract_valid_until"</span>, <span class="st">"contract_left_days"</span>, <span class="st">"days_at_club"</span>)])  <span class="sc">%&gt;%</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_material</span>(<span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class=" lightable-material lightable-striped lightable-hover" style="font-family: &quot;Source Sans Pro&quot;, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> fifa_version </th>
   <th style="text-align:left;"> club_joined </th>
   <th style="text-align:left;"> club_contract_valid_until </th>
   <th style="text-align:right;"> contract_left_days </th>
   <th style="text-align:right;"> days_at_club </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:left;"> 2009-07-01 </td>
   <td style="text-align:left;"> 2021-01-01 </td>
   <td style="text-align:right;"> 1096 </td>
   <td style="text-align:right;"> 3106 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:left;"> 2004-07-01 </td>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4932 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:left;"> 2011-07-01 </td>
   <td style="text-align:left;"> 2021-01-01 </td>
   <td style="text-align:right;"> 1096 </td>
   <td style="text-align:right;"> 2376 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:left;"> 2014-07-11 </td>
   <td style="text-align:left;"> 2021-01-01 </td>
   <td style="text-align:right;"> 1096 </td>
   <td style="text-align:right;"> 1270 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:left;"> 2017-08-03 </td>
   <td style="text-align:left;"> 2022-01-01 </td>
   <td style="text-align:right;"> 1461 </td>
   <td style="text-align:right;"> 151 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-01-01 </td>
   <td style="text-align:left;"> 2014-07-01 </td>
   <td style="text-align:left;"> 2021-01-01 </td>
   <td style="text-align:right;"> 1096 </td>
   <td style="text-align:right;"> 1280 </td>
  </tr>
</tbody>
</table>

</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(player_df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(fifa_version, club_contract_valid_until, club_joined))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="transforming-features" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="transforming-features"><span class="header-section-number">3.2</span> Transforming Features</h2>
<p>The features: body_type and work_rate have string values with mixed types. That can be formatted to generate cleaner categories:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>work_rate <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(player_df<span class="sc">$</span>work_rate, <span class="st">"</span><span class="sc">\\</span><span class="st">w+"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>body_type <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(player_df<span class="sc">$</span>body_type, <span class="st">"</span><span class="sc">\\</span><span class="st">w+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The features of the data have the following types now:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(player_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   18796 obs. of  13 variables:
 $ value_eur               : num  9.55e+07 1.05e+08 6.10e+07 9.70e+07 1.23e+08 9.20e+07 5.20e+07 7.70e+07 7.90e+07 9.05e+07 ...
 $ wage_eur                : num  575000 575000 225000 500000 275000 350000 300000 275000 325000 300000 ...
 $ age                     : int  32 30 31 30 25 28 31 29 27 26 ...
 $ height_cm               : int  185 170 193 182 175 185 183 184 182 173 ...
 $ weight_kg               : int  80 72 92 86 68 79 75 87 78 76 ...
 $ league_name             : chr  "Spain Primera Division" "Spain Primera Division" "German 1. Bundesliga" "Spain Primera Division" ...
 $ preferred_foot          : chr  "Right" "Left" "Right" "Right" ...
 $ international_reputation: int  5 5 5 5 5 4 4 4 4 4 ...
 $ work_rate               : chr  "High" "Medium" "Medium" "High" ...
 $ body_type               : chr  "Unique" "Unique" "Normal" "Normal" ...
 $ release_clause_eur      : num  1.96e+08 2.15e+08 1.01e+08 1.99e+08 2.37e+08 ...
 $ contract_left_days      : num  1096 0 1096 1096 1461 ...
 $ days_at_club            : num  3106 4932 2376 1270 151 ...</code></pre>
</div>
</div>
<p>The features: league_name, preferred_foot, work_rate, body_type and international_reputation can be <em>converted to categorical type</em> to facilitate model fitting.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>league_name <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(player_df<span class="sc">$</span>league_name)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>preferred_foot <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(player_df<span class="sc">$</span>preferred_foot)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>work_rate <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(player_df<span class="sc">$</span>work_rate)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>body_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(player_df<span class="sc">$</span>body_type)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>international_reputation <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(player_df<span class="sc">$</span>international_reputation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="train-test-split" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="train-test-split"><span class="header-section-number">3.3</span> Train-Test Split</h2>
<p>Now the data is ready for splitting into training (including validation) and testing datasets. The test dataset will be utilized later, after designing the models, for predicting the wage on out-of-sample data.</p>
<p>We will select 80% of the data for training, and keep 20% as unseen data for prediction.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample.int</span>(<span class="at">n =</span> <span class="fu">nrow</span>(player_df), <span class="at">size =</span> <span class="fu">floor</span>(.<span class="dv">80</span><span class="sc">*</span><span class="fu">nrow</span>(player_df)), <span class="at">replace =</span> F)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> player_df[sample, ]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>test  <span class="ot">&lt;-</span> player_df[<span class="sc">-</span>sample, ]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>player_df <span class="ot">&lt;-</span> train  <span class="co"># renaming the dataframe</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="fitting-regression-models" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Fitting Regression Models</h1>
<p>Now we will model the dependence of Wage on other covariates. The models will be used to make prediction on the unseen data later.</p>
<section id="linear-model" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="linear-model"><span class="header-section-number">4.1</span> Linear Model</h2>
<div class="cell">
<style type="text/css">
.main-container {
    max-width: 600px !important;
}

pre {
  max-height: 500px !important;
  overflow-y: auto !important;
  overflow-x: scroll !important;
}
pre code {
  white-space: pre
}
</style>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>model.lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage_eur <span class="sc">~</span> ., <span class="at">data=</span>player_df)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>model.lm1.summ <span class="ot">&lt;-</span> <span class="fu">summary</span>(model.lm1)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>model.lm1.summ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage_eur ~ ., data = player_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-245650   -5724     245    4662  239997 

Coefficients:
                                        Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                            3.358e+04  5.074e+03   6.618 3.76e-11
value_eur                              6.064e-04  5.247e-05  11.558  &lt; 2e-16
age                                    8.992e+02  4.068e+01  22.106  &lt; 2e-16
height_cm                             -2.098e+02  3.783e+01  -5.545 2.99e-08
weight_kg                              8.909e+01  3.729e+01   2.389  0.01691
league_nameFrench Ligue 1             -2.036e+04  5.156e+02 -39.482  &lt; 2e-16
league_nameGerman 1. Bundesliga       -1.924e+04  5.262e+02 -36.563  &lt; 2e-16
league_nameHolland Eredivisie         -2.437e+04  5.734e+02 -42.501  &lt; 2e-16
league_nameItalian Serie A            -1.546e+04  5.243e+02 -29.490  &lt; 2e-16
league_namePortuguese Liga ZON SAGRES -2.914e+04  5.580e+02 -52.228  &lt; 2e-16
league_nameSpain Primera Division     -1.959e+04  5.148e+02 -38.061  &lt; 2e-16
preferred_footRight                    9.119e+01  3.310e+02   0.275  0.78296
international_reputation2              7.478e+03  4.528e+02  16.515  &lt; 2e-16
international_reputation3              2.394e+04  7.522e+02  31.824  &lt; 2e-16
international_reputation4              8.325e+04  1.555e+03  53.552  &lt; 2e-16
international_reputation5              1.511e+05  3.942e+03  38.330  &lt; 2e-16
work_rateLow                          -7.862e+02  7.879e+02  -0.998  0.31837
work_rateMedium                       -1.011e+03  3.361e+02  -3.009  0.00263
body_typeNormal                       -2.519e+02  3.325e+02  -0.758  0.44872
body_typeStocky                       -9.086e+02  7.346e+02  -1.237  0.21616
body_typeUnique                       -6.258e+03  1.489e+03  -4.204 2.64e-05
release_clause_eur                     6.297e-04  2.981e-05  21.122  &lt; 2e-16
contract_left_days                     3.008e+00  3.665e-01   8.206 2.47e-16
days_at_club                           1.964e+00  1.984e-01   9.895  &lt; 2e-16
                                         
(Intercept)                           ***
value_eur                             ***
age                                   ***
height_cm                             ***
weight_kg                             *  
league_nameFrench Ligue 1             ***
league_nameGerman 1. Bundesliga       ***
league_nameHolland Eredivisie         ***
league_nameItalian Serie A            ***
league_namePortuguese Liga ZON SAGRES ***
league_nameSpain Primera Division     ***
preferred_footRight                      
international_reputation2             ***
international_reputation3             ***
international_reputation4             ***
international_reputation5             ***
work_rateLow                             
work_rateMedium                       ** 
body_typeNormal                          
body_typeStocky                          
body_typeUnique                       ***
release_clause_eur                    ***
contract_left_days                    ***
days_at_club                          ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17620 on 15012 degrees of freedom
Multiple R-squared:  0.7947,    Adjusted R-squared:  0.7944 
F-statistic:  2527 on 23 and 15012 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see that the features: weight_kg, preferred_foot, work_rate and body_type have low signficance in modelling the wage.</p>
<p>So, let’s try a linear model without these factors:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model.lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage_eur <span class="sc">~</span> value_eur <span class="sc">+</span> age <span class="sc">+</span> height_cm <span class="sc">+</span> league_name <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                  international_reputation <span class="sc">+</span> release_clause_eur <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                  contract_left_days <span class="sc">+</span> days_at_club, <span class="at">data =</span> player_df)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>model.lm2.summ <span class="ot">&lt;-</span> <span class="fu">summary</span>(model.lm2)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>model.lm2.summ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage_eur ~ value_eur + age + height_cm + league_name + 
    international_reputation + release_clause_eur + contract_left_days + 
    days_at_club, data = player_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-247655   -5686     213    4625  239475 

Coefficients:
                                        Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                            2.941e+04  4.055e+03   7.252 4.32e-13
value_eur                              5.426e-04  4.995e-05  10.862  &lt; 2e-16
age                                    9.239e+02  3.947e+01  23.406  &lt; 2e-16
height_cm                             -1.581e+02  2.214e+01  -7.139 9.85e-13
league_nameFrench Ligue 1             -2.039e+04  5.153e+02 -39.562  &lt; 2e-16
league_nameGerman 1. Bundesliga       -1.910e+04  5.239e+02 -36.456  &lt; 2e-16
league_nameHolland Eredivisie         -2.446e+04  5.697e+02 -42.932  &lt; 2e-16
league_nameItalian Serie A            -1.543e+04  5.237e+02 -29.473  &lt; 2e-16
league_namePortuguese Liga ZON SAGRES -2.924e+04  5.555e+02 -52.645  &lt; 2e-16
league_nameSpain Primera Division     -1.969e+04  5.131e+02 -38.381  &lt; 2e-16
international_reputation2              7.662e+03  4.517e+02  16.962  &lt; 2e-16
international_reputation3              2.388e+04  7.520e+02  31.756  &lt; 2e-16
international_reputation4              8.285e+04  1.551e+03  53.404  &lt; 2e-16
international_reputation5              1.484e+05  3.881e+03  38.237  &lt; 2e-16
release_clause_eur                     6.558e-04  2.927e-05  22.404  &lt; 2e-16
contract_left_days                     3.194e+00  3.651e-01   8.747  &lt; 2e-16
days_at_club                           1.969e+00  1.984e-01   9.922  &lt; 2e-16
                                         
(Intercept)                           ***
value_eur                             ***
age                                   ***
height_cm                             ***
league_nameFrench Ligue 1             ***
league_nameGerman 1. Bundesliga       ***
league_nameHolland Eredivisie         ***
league_nameItalian Serie A            ***
league_namePortuguese Liga ZON SAGRES ***
league_nameSpain Primera Division     ***
international_reputation2             ***
international_reputation3             ***
international_reputation4             ***
international_reputation5             ***
release_clause_eur                    ***
contract_left_days                    ***
days_at_club                          ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17640 on 15019 degrees of freedom
Multiple R-squared:  0.7943,    Adjusted R-squared:  0.7941 
F-statistic:  3624 on 16 and 15019 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see that the F-statistic has improved from 2527 to 3624, while Adjusted R-squared reduced from 0.7944 to 0.7941.</p>
<p>We see that the F-statistic has improved substantially, without much reduction in Adjusted R-squared value. So the model got better.</p>
</section>
<section id="generalized-linear-models" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="generalized-linear-models"><span class="header-section-number">4.2</span> Generalized Linear Models</h2>
<p>Since we are working with currency data (wage, value and release_clause), we cannot assume a normal distribution of the covariates (since they are non-negative and dense at low values). Let us plot the univariate distributions:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="FifaWage_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FifaWage_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the currency variables (wage_eur, value_eur and release_clause_eur) are highly positively skewed, and far from normally distributed. Thus we should view them in a log-scale. The distribution after log transformation are shown below:</p>
<section id="log-transformed-variables" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="log-transformed-variables"><span class="header-section-number">4.2.1</span> Log transformed variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>wage_log <span class="ot">&lt;-</span> <span class="fu">log</span>(player_df<span class="sc">$</span>wage_eur)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>value_log <span class="ot">&lt;-</span> <span class="fu">log</span>(player_df<span class="sc">$</span>value_eur)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>player_df<span class="sc">$</span>release_clause_log <span class="ot">&lt;-</span> <span class="fu">log</span>(player_df<span class="sc">$</span>release_clause_eur)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="FifaWage_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the positive skewness has been damped, and the log transformed variables are approximately gaussian.</p>
</section>
<section id="gamma-distributed-response" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="gamma-distributed-response"><span class="header-section-number">4.2.2</span> Gamma Distributed Response</h3>
<p>If we log-transform the response variable (Wage), we will no longer be able to compare the model to the previous linear models where non-transformed Wage was used. It will also introduce extra bias due to nonlinear back-transformation with exponential function. Thus, we will keep the response variable in the original form, and rather fit a GLM with a family corresponding to its distribution.</p>
<p><br></p>
<div class="cell" data-layout-align="left">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>k_wage <span class="ot">&lt;-</span> player_df<span class="sc">$</span>wage_eur<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_df, <span class="fu">aes</span>(<span class="at">x=</span>k_wage)) <span class="sc">+</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density</span>(<span class="at">colour=</span><span class="st">"#ff6699"</span>, <span class="at">geom=</span><span class="st">"line"</span>, <span class="at">position=</span><span class="st">"identity"</span>, <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">color=</span><span class="st">"#0099ff"</span>, <span class="at">fun=</span>dgamma, <span class="at">args=</span><span class="fu">list</span>(<span class="at">shape=</span><span class="fu">mean</span>(k_wage)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sd</span>(k_wage)<span class="sc">^</span><span class="dv">2</span>, <span class="at">scale=</span><span class="fu">sd</span>(k_wage)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">mean</span>(k_wage)), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Gamma distribution of Wage"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Wage (in 1000 Eur)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-wagegamma" class="quarto-figure quarto-figure-left anchored">
<figure class="figure">
<p><img src="FifaWage_files/figure-html/fig-wagegamma-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Distribution of Wage, fitted with a Gamma density function</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Thus, we will fit a GLM with Gamma family, and with a log-link.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model.glm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(wage_eur <span class="sc">~</span> value_log <span class="sc">+</span> age <span class="sc">+</span> height_cm <span class="sc">+</span> league_name <span class="sc">+</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                  international_reputation <span class="sc">+</span> release_clause_log <span class="sc">+</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                  contract_left_days <span class="sc">+</span> days_at_club, <span class="at">data =</span> player_df,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link=</span><span class="st">"log"</span>))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>model.glm1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = wage_eur ~ value_log + age + height_cm + league_name + 
    international_reputation + release_clause_log + contract_left_days + 
    days_at_club, family = Gamma(link = "log"), data = player_df)

Coefficients:
                          (Intercept)                              value_log  
                            2.653e-01                              2.161e-01  
                                  age                              height_cm  
                            6.967e-02                             -4.365e-03  
            league_nameFrench Ligue 1        league_nameGerman 1. Bundesliga  
                           -6.132e-01                             -5.229e-01  
        league_nameHolland Eredivisie             league_nameItalian Serie A  
                           -1.239e+00                             -4.113e-01  
league_namePortuguese Liga ZON SAGRES      league_nameSpain Primera Division  
                           -1.484e+00                             -6.742e-01  
            international_reputation2              international_reputation3  
                            3.867e-02                              1.404e-01  
            international_reputation4              international_reputation5  
                            4.545e-01                              6.118e-01  
                   release_clause_log                     contract_left_days  
                            3.651e-01                              6.394e-05  
                         days_at_club  
                            4.784e-05  

Degrees of Freedom: 15035 Total (i.e. Null);  15019 Residual
Null Deviance:      22430 
Residual Deviance: 2562     AIC: 300900</code></pre>
</div>
</div>
<p>If we compare the AIC of the GLM with the previous Linear Model, we see: <br></p>
<ul>
<li>AIC of GLM (with Gamma family and log link) : 300907 <br></li>
<li>AIC of Linear Model 2 : 336730.2</li>
</ul>
<p>Thus, the GLM has given a better result (lower AIC).</p>
</section>
<section id="aic-based-step-function-for-variable-selection" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="aic-based-step-function-for-variable-selection"><span class="header-section-number">4.2.3</span> AIC-based step function for variable selection</h3>
<p>We can see if the variables we initially omitted after linear model, may be added to the GLM, to reduce the AIC even further. We will start off with only value_log as predictor, and keep adding / removing covariates that reduce AIC.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model.glm1.step <span class="ot">&lt;-</span> <span class="fu">step</span>(<span class="fu">glm</span>(wage_eur <span class="sc">~</span> value_log, <span class="at">data=</span>player_df, <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link=</span><span class="st">"log"</span>)),</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">scope =</span> wage_eur <span class="sc">~</span> value_log <span class="sc">+</span> age <span class="sc">+</span> weight_kg <span class="sc">+</span> height_cm <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                          days_at_club <span class="sc">+</span> contract_left_days <span class="sc">+</span> preferred_foot <span class="sc">+</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                          international_reputation <span class="sc">+</span> work_rate <span class="sc">+</span> body_type <span class="sc">+</span> release_clause_log <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                          league_name,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">direction =</span> <span class="st">"both"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=317023.6
wage_eur ~ value_log

                           Df Deviance    AIC
+ league_name               6   4142.2 311766
+ age                       1   5725.2 314546
+ international_reputation  4   6394.8 315733
+ days_at_club              1   6710.5 316284
+ contract_left_days        1   6912.4 316639
+ weight_kg                 1   6977.4 316754
+ release_clause_log        1   7010.9 316813
+ height_cm                 1   7096.9 316965
+ body_type                 3   7113.1 316997
+ work_rate                 2   7116.4 317001
+ preferred_foot            1   7129.4 317022
&lt;none&gt;                          7131.5 317024
- value_log                 1  22426.9 343985

Step:  AIC=308375.2
wage_eur ~ value_log + league_name

                           Df Deviance    AIC
+ age                       1   2712.7 303756
+ international_reputation  4   3692.8 306930
+ contract_left_days        1   3927.5 307683
+ days_at_club              1   3943.1 307734
+ weight_kg                 1   4061.6 308117
+ body_type                 3   4103.2 308255
+ release_clause_log        1   4132.4 308345
+ height_cm                 1   4134.2 308351
+ work_rate                 2   4136.2 308360
+ preferred_foot            1   4141.1 308374
&lt;none&gt;                          4142.2 308375
- league_name               6   7131.5 318027
- value_log                 1  14989.6 343442

Step:  AIC=301775.6
wage_eur ~ value_log + league_name + age

                           Df Deviance    AIC
+ release_clause_log        1   2651.0 301468
+ international_reputation  4   2655.9 301498
+ days_at_club              1   2692.9 301678
+ height_cm                 1   2700.6 301717
+ weight_kg                 1   2707.9 301754
+ work_rate                 2   2707.9 301755
+ body_type                 3   2707.6 301756
+ contract_left_days        1   2710.0 301764
+ preferred_foot            1   2712.0 301774
&lt;none&gt;                          2712.7 301776
- age                       1   4142.2 308954
- league_name               6   5725.2 316895
- value_log                 1  12195.5 349404

Step:  AIC=301421.4
wage_eur ~ value_log + league_name + age + release_clause_log

                           Df Deviance    AIC
+ international_reputation  4   2593.8 301136
+ days_at_club              1   2628.2 301307
+ height_cm                 1   2639.9 301367
+ body_type                 3   2643.6 301389
+ work_rate                 2   2646.0 301400
+ weight_kg                 1   2646.9 301402
+ contract_left_days        1   2649.7 301417
+ preferred_foot            1   2650.1 301419
&lt;none&gt;                          2651.0 301421
- value_log                 1   2681.4 301576
- release_clause_log        1   2712.7 301736
- age                       1   4132.4 309023
- league_name               6   5485.3 315957

Step:  AIC=301092.2
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation

                           Df Deviance    AIC
+ days_at_club              1   2581.1 301026
+ height_cm                 1   2582.9 301036
+ weight_kg                 1   2589.2 301069
+ work_rate                 2   2589.1 301071
+ contract_left_days        1   2591.1 301080
+ body_type                 3   2591.5 301086
+ preferred_foot            1   2593.0 301090
&lt;none&gt;                          2593.8 301092
- value_log                 1   2618.9 301224
- international_reputation  4   2651.0 301389
- release_clause_log        1   2655.9 301421
- age                       1   3674.9 306858
- league_name               6   5331.1 315685

Step:  AIC=301017.8
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation + days_at_club

                           Df Deviance    AIC
+ height_cm                 1   2570.5 300963
+ contract_left_days        1   2573.7 300980
+ work_rate                 2   2575.6 300993
+ weight_kg                 1   2576.7 300996
+ body_type                 3   2578.8 301012
+ preferred_foot            1   2580.1 301015
&lt;none&gt;                          2581.1 301018
- days_at_club              1   2593.8 301084
- value_log                 1   2604.4 301141
- international_reputation  4   2628.2 301263
- release_clause_log        1   2645.4 301361
- age                       1   3577.6 306368
- league_name               6   5221.2 315186

Step:  AIC=300956.3
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation + days_at_club + height_cm

                           Df Deviance    AIC
+ contract_left_days        1   2562.0 300912
+ work_rate                 2   2568.2 300948
+ body_type                 3   2568.3 300951
+ preferred_foot            1   2570.0 300956
+ weight_kg                 1   2570.0 300956
&lt;none&gt;                          2570.5 300956
- height_cm                 1   2581.1 301011
- days_at_club              1   2582.9 301021
- value_log                 1   2594.3 301083
- international_reputation  4   2617.6 301202
- release_clause_log        1   2633.7 301295
- age                       1   3575.0 306366
- league_name               6   5221.2 315226

Step:  AIC=300907
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation + days_at_club + height_cm + contract_left_days

                           Df Deviance    AIC
+ work_rate                 2   2559.9 300900
+ body_type                 3   2559.7 300901
+ preferred_foot            1   2561.5 300907
+ weight_kg                 1   2561.6 300907
&lt;none&gt;                          2562.0 300907
- contract_left_days        1   2570.5 300951
- height_cm                 1   2573.7 300969
- days_at_club              1   2579.4 300999
- value_log                 1   2585.2 301031
- international_reputation  4   2610.0 301159
- release_clause_log        1   2622.4 301232
- age                       1   3515.4 306058
- league_name               6   5205.3 315181

Step:  AIC=300898.4
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation + days_at_club + height_cm + contract_left_days + 
    work_rate

                           Df Deviance    AIC
+ body_type                 3   2557.7 300893
+ weight_kg                 1   2559.4 300898
&lt;none&gt;                          2559.9 300898
+ preferred_foot            1   2559.5 300899
- work_rate                 2   2562.0 300906
- contract_left_days        1   2568.2 300942
- height_cm                 1   2568.3 300942
- days_at_club              1   2577.9 300994
- value_log                 1   2582.5 301019
- international_reputation  4   2607.6 301149
- release_clause_log        1   2620.6 301225
- age                       1   3510.4 306039
- league_name               6   5190.7 315121

Step:  AIC=300891.3
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation + days_at_club + height_cm + contract_left_days + 
    work_rate + body_type

                           Df Deviance    AIC
+ weight_kg                 1   2556.3 300886
&lt;none&gt;                          2557.7 300891
+ preferred_foot            1   2557.4 300892
- body_type                 3   2559.9 300897
- work_rate                 2   2559.7 300898
- contract_left_days        1   2566.1 300935
- height_cm                 1   2566.1 300935
- days_at_club              1   2575.7 300987
- value_log                 1   2580.3 301011
- international_reputation  4   2601.4 301120
- release_clause_log        1   2617.5 301213
- age                       1   3495.2 305970
- league_name               6   5155.1 314957

Step:  AIC=300885
wage_eur ~ value_log + league_name + age + release_clause_log + 
    international_reputation + days_at_club + height_cm + contract_left_days + 
    work_rate + body_type + weight_kg

                           Df Deviance    AIC
&lt;none&gt;                          2556.3 300885
+ preferred_foot            1   2556.0 300885
- weight_kg                 1   2557.7 300890
- work_rate                 2   2558.4 300892
- body_type                 3   2559.4 300896
- height_cm                 1   2563.6 300923
- contract_left_days        1   2564.7 300928
- days_at_club              1   2574.3 300981
- value_log                 1   2578.7 301005
- international_reputation  4   2599.3 301110
- release_clause_log        1   2616.3 301208
- age                       1   3457.1 305770
- league_name               6   5132.2 314847</code></pre>
</div>
</div>
<p>In the final model, only preferred_foot is the omitted variable. We include all other features in the GLM. Thus we form the next GLM:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model.glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(wage_eur <span class="sc">~</span> value_log <span class="sc">+</span> age <span class="sc">+</span> height_cm <span class="sc">+</span> league_name <span class="sc">+</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                    international_reputation <span class="sc">+</span> release_clause_log <span class="sc">+</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                    contract_left_days <span class="sc">+</span> days_at_club <span class="sc">+</span> weight_kg <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                    work_rate <span class="sc">+</span> body_type, <span class="at">data =</span> player_df,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link=</span><span class="st">"log"</span>))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>model.glm2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = wage_eur ~ value_log + age + height_cm + league_name + 
    international_reputation + release_clause_log + contract_left_days + 
    days_at_club + weight_kg + work_rate + body_type, family = Gamma(link = "log"), 
    data = player_df)

Coefficients:
                          (Intercept)                              value_log  
                            4.161e-01                              2.137e-01  
                                  age                              height_cm  
                            6.968e-02                             -5.831e-03  
            league_nameFrench Ligue 1        league_nameGerman 1. Bundesliga  
                           -6.110e-01                             -5.223e-01  
        league_nameHolland Eredivisie             league_nameItalian Serie A  
                           -1.232e+00                             -4.096e-01  
league_namePortuguese Liga ZON SAGRES      league_nameSpain Primera Division  
                           -1.477e+00                             -6.686e-01  
            international_reputation2              international_reputation3  
                            3.760e-02                              1.412e-01  
            international_reputation4              international_reputation5  
                            4.504e-01                              6.046e-01  
                   release_clause_log                     contract_left_days  
                            3.651e-01                              6.326e-05  
                         days_at_club                              weight_kg  
                            4.859e-05                              2.469e-03  
                         work_rateLow                        work_rateMedium  
                           -4.343e-02                             -2.540e-02  
                      body_typeNormal                        body_typeStocky  
                           -3.286e-02                             -1.957e-02  
                      body_typeUnique  
                           -2.678e-02  

Degrees of Freedom: 15035 Total (i.e. Null);  15013 Residual
Null Deviance:      22430 
Residual Deviance: 2556     AIC: 300900</code></pre>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="random-forest-model" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="random-forest-model"><span class="header-section-number">4.3</span> Random Forest Model</h2>
<!-- ![img src: www.frontiersin.org/articles/10.3389/fnagi.2017.00329/full](images/random-forest.jpg){#fig-fifa22} -->
<p>In the next stage, we will try to fit a random forest regression model for Wage analysis. The code is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model.rf1 <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(wage_eur <span class="sc">~</span> value_log <span class="sc">+</span> age <span class="sc">+</span> height_cm <span class="sc">+</span> league_name <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                            international_reputation <span class="sc">+</span> release_clause_log <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                            contract_left_days <span class="sc">+</span> days_at_club, <span class="at">data=</span>player_df, <span class="at">ntree=</span><span class="dv">100</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">keep.forest=</span><span class="cn">TRUE</span>, <span class="at">importance=</span><span class="cn">TRUE</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>model.rf1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = wage_eur ~ value_log + age + height_cm +      league_name + international_reputation + release_clause_log +      contract_left_days + days_at_club, data = player_df, ntree = 100,      keep.forest = TRUE, importance = TRUE) 
               Type of random forest: regression
                     Number of trees: 100
No. of variables tried at each split: 2

          Mean of squared residuals: 199624051
                    % Var explained: 86.79</code></pre>
</div>
</div>
<!-- We see that this model explains 87.48% of the variance, which indicates good performance. -->
<section id="hyperparameter-optimization-of-random-forest-model" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="hyperparameter-optimization-of-random-forest-model"><span class="header-section-number">4.3.1</span> Hyperparameter Optimization of Random Forest Model</h3>
<p>One main hyperparameter we can tune in the Random Forest Model is mtry: the number of variables to randomly sample as candidates at each split. By default, it is set as p/3 where p is the number of features used in the model.</p>
<p>The best value of mtry can be found by finding the mtry corresponding to the minimum of OOB Error, using the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>bestmtry <span class="ot">&lt;-</span> <span class="fu">tuneRF</span>(player_df,player_df<span class="sc">$</span>wage_eur,<span class="at">stepFactor =</span> <span class="fl">1.2</span>,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">improve =</span> <span class="fl">0.01</span>, <span class="at">trace=</span>T, <span class="at">plot=</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mtry = 5  OOB error = 3196052 
Searching left ...
Searching right ...
mtry = 6    OOB error = 1781462 
0.4426054 0.01 
mtry = 7    OOB error = 1596746 
0.1036878 0.01 
mtry = 8    OOB error = 1510160 
0.05422675 0.01 
mtry = 9    OOB error = 2068916 
-0.3699981 0.01 </code></pre>
</div>
<div class="cell-output-display">
<div id="fig-rftuner" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="FifaWage_files/figure-html/fig-rftuner-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Random Forest tuning for best mtry value</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We see that best mtry value is 8. Using that in the improved Random Forest model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model.rf2 <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(wage_eur <span class="sc">~</span> value_log <span class="sc">+</span> age <span class="sc">+</span> height_cm <span class="sc">+</span> league_name <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                            international_reputation <span class="sc">+</span> release_clause_log <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                            contract_left_days <span class="sc">+</span> days_at_club, <span class="at">data=</span>player_df, <span class="at">ntree=</span><span class="dv">100</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">mtry=</span><span class="dv">8</span>, <span class="at">keep.forest=</span><span class="cn">TRUE</span>, <span class="at">importance=</span><span class="cn">TRUE</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>model.rf2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = wage_eur ~ value_log + age + height_cm +      league_name + international_reputation + release_clause_log +      contract_left_days + days_at_club, data = player_df, ntree = 100,      mtry = 8, keep.forest = TRUE, importance = TRUE) 
               Type of random forest: regression
                     Number of trees: 100
No. of variables tried at each split: 8

          Mean of squared residuals: 198204509
                    % Var explained: 86.88</code></pre>
</div>
</div>
</section>
<section id="visualizing-variable-importance" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="visualizing-variable-importance"><span class="header-section-number">4.3.2</span> Visualizing variable importance</h3>
<p>The importance of variables used in the random forest model is visualized below:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ImpData <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">importance</span>(model.rf2))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ImpData<span class="sc">$</span>Var.Names <span class="ot">&lt;-</span> <span class="fu">row.names</span>(ImpData)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ImpData, <span class="fu">aes</span>(<span class="at">x=</span>Var.Names, <span class="at">y=</span><span class="st">`</span><span class="at">%IncMSE</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>( <span class="fu">aes</span>(<span class="at">x=</span>Var.Names, <span class="at">xend=</span>Var.Names, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="st">`</span><span class="at">%IncMSE</span><span class="st">`</span>), <span class="at">color=</span><span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> IncNodePurity), <span class="at">color=</span><span class="st">"blue"</span>, <span class="at">alpha=</span><span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position=</span><span class="st">"bottom"</span>,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>()</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-featureimp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="FifaWage_files/figure-html/fig-featureimp-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Variable importance</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Here we see 2 different metrics for assessing Variable Importance:</p>
<ul>
<li><em>%IncMSE</em> : Increase in MSE of predictions when the variable is permuted</li>
<li><em>IncNodePurity</em> : Average increase in node purity on splitting using the variable</li>
</ul>
<p>%IncMSE is the more relevant metric, and we see that league_name plays most important role in the wage : permutations (shuffling) of the league_name can result in highest changes of Wage. That is followed by the international_reputation.</p>
</section>
</section>
<section id="xgboost-model" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="xgboost-model"><span class="header-section-number">4.4</span> XGBoost Model</h2>
<p>Next we use XGBoost (eXtreme Gradient Boosting) algorithm to design a model for Wage prediction. We will tune the parameters: max.depth and nrounds of the gradient boosting algorithm using grid search, and evaluating MAPE on a validation dataset. The model with best parameter choices are selected for evaluating on the test set later.</p>
<p>We convert the categorical variables to dummy variables since the XGBoost model requires a data matrix with numerical features. This is achieved with the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>dummy_player_df <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(player_df, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">'league_name'</span>, <span class="st">'international_reputation'</span>, <span class="st">'work_rate'</span>, <span class="st">'body_type'</span>, <span class="st">'preferred_foot'</span>),</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">remove_selected_columns =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we keep aside a portion of the data for validation, and generate data matrices for XGBoost:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample.int</span>(<span class="at">n =</span> <span class="fu">nrow</span>(dummy_player_df), <span class="at">size =</span> <span class="fu">floor</span>(.<span class="dv">80</span><span class="sc">*</span><span class="fu">nrow</span>(dummy_player_df)), <span class="at">replace =</span> F)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>train_xgb <span class="ot">&lt;-</span> dummy_player_df[sample, ]</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>val_xgb  <span class="ot">&lt;-</span> dummy_player_df[<span class="sc">-</span>sample, ]</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>train_xgb_x <span class="ot">&lt;-</span> <span class="fu">data.matrix</span>(train_xgb[, <span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(train_xgb) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'value_eur'</span>, <span class="st">'wage_eur'</span>, <span class="st">'wage_log'</span>, <span class="st">'release_clause_eur'</span>))])</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>train_xgb_y <span class="ot">&lt;-</span> train_xgb<span class="sc">$</span>wage_eur</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>val_xgb_x <span class="ot">&lt;-</span> <span class="fu">data.matrix</span>(val_xgb[, <span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(val_xgb) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'value_eur'</span>, <span class="st">'wage_eur'</span>, <span class="st">'wage_log'</span>, <span class="st">'release_clause_eur'</span>))])</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>val_xgb_y <span class="ot">&lt;-</span> val_xgb<span class="sc">$</span>wage_eur</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>xgb_train <span class="ot">=</span> <span class="fu">xgb.DMatrix</span>(<span class="at">data =</span> train_xgb_x, <span class="at">label =</span> train_xgb_y)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>xgb_val <span class="ot">=</span> <span class="fu">xgb.DMatrix</span>(<span class="at">data =</span> val_xgb_x, <span class="at">label =</span> val_xgb_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>To tune the max.depth and nrounds parameters of thr XGBoost model, we create a function: grid_search_xgb_val to display the MAPE for a particular (max.depth, nrounds) input:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>grid_search_xgb_val <span class="ot">&lt;-</span> <span class="cf">function</span>(depth, rounds){</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  model_xgboost <span class="ot">=</span> <span class="fu">xgboost</span>(<span class="at">data =</span> xgb_train, <span class="at">max.depth =</span> depth, <span class="at">nrounds =</span> rounds, <span class="at">verbose =</span> <span class="dv">0</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  pred_y <span class="ot">=</span> <span class="fu">predict</span>(model_xgboost, xgb_val)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Depth:%d   Rounds:%d   MAPE:%f</span><span class="sc">\n</span><span class="st">"</span>, depth, rounds, <span class="fu">MAPE</span>(pred_y, val_xgb_y)<span class="sc">*</span><span class="dv">100</span>))</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(<span class="st">"depth"</span> <span class="ot">=</span> depth, <span class="st">"rounds"</span> <span class="ot">=</span> rounds, <span class="st">"mape"</span> <span class="ot">=</span> <span class="fu">MAPE</span>(pred_y, val_xgb_y)<span class="sc">*</span><span class="dv">100</span>))</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Performing grid search with various values of max.depth and nrounds:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>opt_depth <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>opt_rounds <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>min_mape <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (depth <span class="cf">in</span> <span class="fu">seq</span>(<span class="dv">3</span>,<span class="dv">12</span>,<span class="at">by=</span><span class="dv">1</span>)) {</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (rounds <span class="cf">in</span> <span class="fu">seq</span>(<span class="dv">40</span>,<span class="dv">160</span>, <span class="at">by=</span><span class="dv">20</span>)) {</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> <span class="fu">grid_search_xgb_val</span>(depth,rounds)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(result<span class="sc">$</span>mape <span class="sc">&lt;</span> min_mape) {</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>      min_mape <span class="ot">&lt;-</span> result<span class="sc">$</span>mape</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>      opt_depth <span class="ot">&lt;-</span> result<span class="sc">$</span>depth</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>      opt_rounds <span class="ot">&lt;-</span> result<span class="sc">$</span>rounds</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"New record:-- Depth:%d   Rounds:%d   MAPE:%f</span><span class="sc">\n</span><span class="st">"</span>, opt_depth, opt_rounds, min_mape))</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Depth:3   Rounds:40   MAPE:42.309333
New record:-- Depth:3   Rounds:40   MAPE:42.309333
Depth:3   Rounds:60   MAPE:42.222445
New record:-- Depth:3   Rounds:60   MAPE:42.222445
Depth:3   Rounds:80   MAPE:41.666486
New record:-- Depth:3   Rounds:80   MAPE:41.666486
Depth:3   Rounds:100   MAPE:41.813389
Depth:3   Rounds:120   MAPE:41.084658
New record:-- Depth:3   Rounds:120   MAPE:41.084658
Depth:3   Rounds:140   MAPE:40.590522
New record:-- Depth:3   Rounds:140   MAPE:40.590522
Depth:3   Rounds:160   MAPE:40.268984
New record:-- Depth:3   Rounds:160   MAPE:40.268984
Depth:4   Rounds:40   MAPE:36.439804
New record:-- Depth:4   Rounds:40   MAPE:36.439804
Depth:4   Rounds:60   MAPE:35.141178
New record:-- Depth:4   Rounds:60   MAPE:35.141178
Depth:4   Rounds:80   MAPE:34.870408
New record:-- Depth:4   Rounds:80   MAPE:34.870408
Depth:4   Rounds:100   MAPE:34.589336
New record:-- Depth:4   Rounds:100   MAPE:34.589336
Depth:4   Rounds:120   MAPE:34.621300
Depth:4   Rounds:140   MAPE:34.695299
Depth:4   Rounds:160   MAPE:34.750275
Depth:5   Rounds:40   MAPE:34.996525
Depth:5   Rounds:60   MAPE:34.714891
Depth:5   Rounds:80   MAPE:34.891669
Depth:5   Rounds:100   MAPE:35.334966
Depth:5   Rounds:120   MAPE:35.276264
Depth:5   Rounds:140   MAPE:35.583056
Depth:5   Rounds:160   MAPE:35.772319
Depth:6   Rounds:40   MAPE:34.975921
Depth:6   Rounds:60   MAPE:34.551006
New record:-- Depth:6   Rounds:60   MAPE:34.551006
Depth:6   Rounds:80   MAPE:34.760077
Depth:6   Rounds:100   MAPE:34.986647
Depth:6   Rounds:120   MAPE:35.018111
Depth:6   Rounds:140   MAPE:35.193605
Depth:6   Rounds:160   MAPE:35.321599
Depth:7   Rounds:40   MAPE:34.530259
New record:-- Depth:7   Rounds:40   MAPE:34.530259
Depth:7   Rounds:60   MAPE:34.643383
Depth:7   Rounds:80   MAPE:35.062626
Depth:7   Rounds:100   MAPE:35.420850
Depth:7   Rounds:120   MAPE:35.901167
Depth:7   Rounds:140   MAPE:36.114789
Depth:7   Rounds:160   MAPE:36.265276
Depth:8   Rounds:40   MAPE:34.620141
Depth:8   Rounds:60   MAPE:34.850971
Depth:8   Rounds:80   MAPE:35.349112
Depth:8   Rounds:100   MAPE:35.902885
Depth:8   Rounds:120   MAPE:36.182229
Depth:8   Rounds:140   MAPE:36.627765
Depth:8   Rounds:160   MAPE:36.831777
Depth:9   Rounds:40   MAPE:34.143638
New record:-- Depth:9   Rounds:40   MAPE:34.143638
Depth:9   Rounds:60   MAPE:34.474756
Depth:9   Rounds:80   MAPE:35.609511
Depth:9   Rounds:100   MAPE:36.431981
Depth:9   Rounds:120   MAPE:36.886884
Depth:9   Rounds:140   MAPE:37.297243
Depth:9   Rounds:160   MAPE:37.520472
Depth:10   Rounds:40   MAPE:34.737650
Depth:10   Rounds:60   MAPE:35.164351
Depth:10   Rounds:80   MAPE:35.574821
Depth:10   Rounds:100   MAPE:35.966919
Depth:10   Rounds:120   MAPE:36.110516
Depth:10   Rounds:140   MAPE:36.428465
Depth:10   Rounds:160   MAPE:36.472436
Depth:11   Rounds:40   MAPE:35.098951
Depth:11   Rounds:60   MAPE:35.619548
Depth:11   Rounds:80   MAPE:35.867179
Depth:11   Rounds:100   MAPE:36.144776
Depth:11   Rounds:120   MAPE:36.403334
Depth:11   Rounds:140   MAPE:36.581303
Depth:11   Rounds:160   MAPE:36.662512
Depth:12   Rounds:40   MAPE:35.783781
Depth:12   Rounds:60   MAPE:36.057344
Depth:12   Rounds:80   MAPE:36.212657
Depth:12   Rounds:100   MAPE:36.261438
Depth:12   Rounds:120   MAPE:36.311256
Depth:12   Rounds:140   MAPE:36.330095
Depth:12   Rounds:160   MAPE:36.375912</code></pre>
</div>
</div>
<p>From the console output, we see that the minimum MAPE (34.1436382) is obtained for max.depth = 9 and nrounds = 40. Thus, we will create an XGBoost model with those hyperparameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model.xgboost <span class="ot">=</span> <span class="fu">xgboost</span>(<span class="at">data =</span> xgb_train, <span class="at">max.depth =</span> opt_depth, <span class="at">nrounds =</span> opt_rounds, <span class="at">verbose =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
</section>
<section id="wage-prediction" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Wage Prediction</h1>
<p>Using the models we have created, we will predict the Wage on unseen data (unseen during model fitting), and compare MAPE: The Mean Absolute Percentage Error.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>wage_log <span class="ot">&lt;-</span> <span class="fu">log</span>(test<span class="sc">$</span>wage_eur)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>value_log <span class="ot">&lt;-</span> <span class="fu">log</span>(test<span class="sc">$</span>value_eur)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>release_clause_log <span class="ot">&lt;-</span> <span class="fu">log</span>(test<span class="sc">$</span>release_clause_eur)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="baseline-model-prediction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="baseline-model-prediction"><span class="header-section-number">5.1</span> Baseline Model Prediction</h2>
<p>To get a minimum performance (baseline) for wage prediction, we can use the mean wage from training dataset, and use that as prediction in the test data.</p>
<p>Mean wage from training data :26970.73. We can calculate the MAPE using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">mean</span>(player_df<span class="sc">$</span>wage_eur), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 421.7984</code></pre>
</div>
</div>
<p>Thus, the baseline MAPE is 421.798. Any model we propose should have MAPE less than this, to be considered useful.</p>
</section>
<section id="linear-models-prediction" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="linear-models-prediction"><span class="header-section-number">5.2</span> Linear Models Prediction</h2>
<p>Using the first linear model (where we used all covariates), we obtain the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.lm1, test), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 93.49752</code></pre>
</div>
</div>
<p>Using the second linear model (with only significant features selected), we obtain the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.lm2, test), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 93.25372</code></pre>
</div>
</div>
<p>We see that both linear models have more than 80% MAPE. That is not a very good performance.</p>
</section>
<section id="generalized-linear-models-prediction" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="generalized-linear-models-prediction"><span class="header-section-number">5.3</span> Generalized Linear Models Prediction</h2>
<p>Using the first glm (without AIC-based feature selection), we get the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.glm1, test, <span class="at">type =</span> <span class="st">"response"</span>), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.50448</code></pre>
</div>
</div>
<p>Using the second glm (with AIC-based feature selection), we get the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.glm2, test, <span class="at">type =</span> <span class="st">"response"</span>), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.5349</code></pre>
</div>
</div>
<p>We see a drastic improvement in performance using the GLM model, since it used Gamma distribution to model the Wage, with a log-link. This indeed helped in improving the model.</p>
</section>
<section id="random-forest-model-prediction" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="random-forest-model-prediction"><span class="header-section-number">5.4</span> Random Forest Model Prediction</h2>
<p>Using the first random forest model (without hyperparameter optimization), we get the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.rf1, test), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38.32406</code></pre>
</div>
</div>
<p>Using the random forest model after hyperparameter optimization, we get the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.rf2, test), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.45257</code></pre>
</div>
</div>
</section>
<section id="xgboost-model-prediction" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="xgboost-model-prediction"><span class="header-section-number">5.5</span> XGBoost Model Prediction</h2>
<p>We create dummy variables for categorical features in the test dataset, to be able to use the XGBoost model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>dummy_test <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(test, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">'league_name'</span>, <span class="st">'international_reputation'</span>, <span class="st">'work_rate'</span>, <span class="st">'body_type'</span>, <span class="st">'preferred_foot'</span>),</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">remove_selected_columns =</span> <span class="cn">TRUE</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>test_x <span class="ot">&lt;-</span> <span class="fu">data.matrix</span>(dummy_test[, <span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(dummy_test) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'value_eur'</span>, <span class="st">'wage_eur'</span>, <span class="st">'wage_log'</span>, <span class="st">'release_clause_eur'</span>))])</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>test_y <span class="ot">&lt;-</span> test<span class="sc">$</span>wage_eur</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>xgb_test <span class="ot">=</span> <span class="fu">xgb.DMatrix</span>(<span class="at">data =</span> test_x, <span class="at">label =</span> test_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Using the XGBoost model for wage prediction, we get the following MAPE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MAPE</span>(<span class="fu">predict</span>(model.xgboost, xgb_test), test<span class="sc">$</span>wage_eur)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36.54885</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">5.6</span> Conclusion</h2>
<p>Out of all the models we evaluated on the test set; the Random Forest model (after hyperparameter tuning) gave the best MAPE result. The scatter-plot of predicted wage v/s actual wage on unseen data is as shown below:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(test, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">predict</span>(model.rf2, test), <span class="at">y=</span>wage_eur)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">'Predicted Wage'</span>, <span class="at">y=</span><span class="st">'Actual Wage'</span>, <span class="at">title=</span><span class="st">'Predicted vs. Actual Wage with Random Forest Model'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-predactscatter" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="FifaWage_files/figure-html/fig-predactscatter-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;7: Scatter-plot of Predicted v/s Actual Wage with Random Forest Model</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>